//
//  File generated by HDevelop for HALCON/DOTNET (C#) Version 12.0
//


using System;
using HalconDotNet;
namespace HOperatorSet_EX
{

    public partial class HOperatorSet_Ex
    {
        // Chapter: Resistor-Verification
        // Short Description: Translate the shape model contour to its reference pose 
        public static void get_shape_model_contour_ref(HObject ho_ModelRegion, out HObject ho_ModelContoursTrans,
            HTuple hv_ModelID)
        {




            // Local iconic variables 

            HObject ho_ModelContours;

            // Local control variables 

            HTuple hv_ExpDefaultCtrlDummyVar = null, hv_Row = null;
            HTuple hv_Column = null, hv_HomMat2DIdentity = null, hv_HomMat2DTranslate = null;
            // Initialize local and output iconic variables 
            HOperatorSet.GenEmptyObj(out ho_ModelContoursTrans);
            HOperatorSet.GenEmptyObj(out ho_ModelContours);
            HOperatorSet.AreaCenter(ho_ModelRegion, out hv_ExpDefaultCtrlDummyVar, out hv_Row,
                out hv_Column);
            ho_ModelContours.Dispose();
            HOperatorSet.GetShapeModelContours(out ho_ModelContours, hv_ModelID, 1);
            HOperatorSet.HomMat2dIdentity(out hv_HomMat2DIdentity);
            HOperatorSet.HomMat2dTranslate(hv_HomMat2DIdentity, hv_Row, hv_Column, out hv_HomMat2DTranslate);
            ho_ModelContoursTrans.Dispose();
            HOperatorSet.AffineTransContourXld(ho_ModelContours, out ho_ModelContoursTrans,
                hv_HomMat2DTranslate);
            ho_ModelContours.Dispose();

            return;
        }

    }
}