//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSetController {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserSetController.en-us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Buffer Log 的本地化字符串。
        /// </summary>
        internal static string btnBuffer {
            get {
                return ResourceManager.GetString("btnBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        internal static string btnLoad {
            get {
                return ResourceManager.GetString("btnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day Log 的本地化字符串。
        /// </summary>
        internal static string btnNowNote {
            get {
                return ResourceManager.GetString("btnNowNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string labelCostTime {
            get {
                return ResourceManager.GetString("labelCostTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string labelCount {
            get {
                return ResourceManager.GetString("labelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserName 的本地化字符串。
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserSelect 的本地化字符串。
        /// </summary>
        internal static string labelUserSelect {
            get {
                return ResourceManager.GetString("labelUserSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yield 的本地化字符串。
        /// </summary>
        internal static string labelYield {
            get {
                return ResourceManager.GetString("labelYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        internal static string tabRun {
            get {
                return ResourceManager.GetString("tabRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibration Set 的本地化字符串。
        /// </summary>
        internal static string toolCalibration {
            get {
                return ResourceManager.GetString("toolCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Camera Set 的本地化字符串。
        /// </summary>
        internal static string toolCamera {
            get {
                return ResourceManager.GetString("toolCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string toolChinese {
            get {
                return ResourceManager.GetString("toolChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string toolClose {
            get {
                return ResourceManager.GetString("toolClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control 的本地化字符串。
        /// </summary>
        internal static string toolControl {
            get {
                return ResourceManager.GetString("toolControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string toolEnglish {
            get {
                return ResourceManager.GetString("toolEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string toolHelp {
            get {
                return ResourceManager.GetString("toolHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string toolLanguage {
            get {
                return ResourceManager.GetString("toolLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string toolLog {
            get {
                return ResourceManager.GetString("toolLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string toolLogin {
            get {
                return ResourceManager.GetString("toolLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogOff 的本地化字符串。
        /// </summary>
        internal static string toolLogoff {
            get {
                return ResourceManager.GetString("toolLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage 的本地化字符串。
        /// </summary>
        internal static string toolManage {
            get {
                return ResourceManager.GetString("toolManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Motor Set 的本地化字符串。
        /// </summary>
        internal static string toolMotor {
            get {
                return ResourceManager.GetString("toolMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter Set 的本地化字符串。
        /// </summary>
        internal static string toolParam {
            get {
                return ResourceManager.GetString("toolParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Set 的本地化字符串。
        /// </summary>
        internal static string toolProduct {
            get {
                return ResourceManager.GetString("toolProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SerialPort Set 的本地化字符串。
        /// </summary>
        internal static string toolSerialPort {
            get {
                return ResourceManager.GetString("toolSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string toolSet {
            get {
                return ResourceManager.GetString("toolSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket Set 的本地化字符串。
        /// </summary>
        internal static string toolSocket {
            get {
                return ResourceManager.GetString("toolSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string toolStart {
            get {
                return ResourceManager.GetString("toolStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string toolStop {
            get {
                return ResourceManager.GetString("toolStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Set 的本地化字符串。
        /// </summary>
        internal static string toolTeach {
            get {
                return ResourceManager.GetString("toolTeach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string toolTest {
            get {
                return ResourceManager.GetString("toolTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string toolUser {
            get {
                return ResourceManager.GetString("toolUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string toolView {
            get {
                return ResourceManager.GetString("toolView", resourceCulture);
            }
        }
    }
}
